package service;

public enum AuthStatus {
    SUCCESS,
    EMPTY_FIELDS,
    INVALID_CREDENTIALS,
    EMAIL_NOT_VERIFIED,
    STAFF_NOT_APPROVED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_BANNED,
    ACCOUNT_REJECTED,
    DUPLICATE_EMAIL,
    DUPLICATE_USERNAME,
    INVALID_EMAIL,
    WEAK_PASSWORD
}
