package gui.admin;

import java.awt.*;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.border.EmptyBorder;
import gui.components.RoundedButton;

final class AdminUi {
    static final Color GREEN=new Color(55,70,56), PAPER=new Color(252,252,247), LINE=new Color(226,230,221);
    static JLabel label(String text,int size,boolean bold) { JLabel l=new JLabel(text);l.setFont(new Font("Fira Code",bold?Font.BOLD:Font.PLAIN,size));l.setForeground(GREEN);l.putClientProperty("html.disable",true);return l; }
    static JPanel card() { JPanel p=new JPanel(new BorderLayout(0,12)) {
        protected void paintComponent(Graphics g) {Graphics2D d=(Graphics2D)g.create();d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);d.setColor(PAPER);d.fillRoundRect(0,0,getWidth(),getHeight(),22,22);d.dispose();}
    };p.setOpaque(false);p.setBorder(new EmptyBorder(16,16,16,16));p.setAlignmentX(0);return p; }
    static RoundedButton button(String text) {RoundedButton b=new RoundedButton(text,new Color(28,31,27),Color.WHITE);b.setHoverColor(new Color(65,75,63));b.setFont(new Font("Fira Code",Font.BOLD,11));b.setPreferredSize(new Dimension(Math.max(130,text.length()*8+24),40));return b;}
    static JPanel metrics(String... pairs) {JPanel row=new JPanel(new GridLayout(1,pairs.length/2,16,0));row.setOpaque(false);row.setAlignmentX(0);row.setMaximumSize(new Dimension(Integer.MAX_VALUE,104));row.setPreferredSize(new Dimension(900,104));for(int i=0;i<pairs.length;i+=2){JPanel c=card();c.add(label(pairs[i],24,true));c.add(label(pairs[i+1],11,false),BorderLayout.SOUTH);row.add(c);}return row;}
    static void style(JTable t) {
        t.setFont(new Font("Fira Code",Font.PLAIN,11));t.setRowHeight(54);t.setShowVerticalLines(false);t.setShowHorizontalLines(true);t.setGridColor(LINE);t.setIntercellSpacing(new Dimension(0,1));t.setBackground(PAPER);t.setSelectionBackground(new Color(222,231,217));t.setSelectionForeground(GREEN);t.setFillsViewportHeight(true);t.setAutoCreateRowSorter(true);t.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        t.getTableHeader().setFont(new Font("Fira Code",Font.BOLD,11));t.getTableHeader().setBackground(new Color(235,238,229));t.getTableHeader().setPreferredSize(new Dimension(100,42));t.getTableHeader().setReorderingAllowed(false);
        DefaultTableCellRenderer r=new DefaultTableCellRenderer(){public Component getTableCellRendererComponent(JTable table,Object value,boolean selected,boolean focus,int row,int col){super.getTableCellRendererComponent(table,value,selected,focus,row,col);setBorder(new EmptyBorder(8,12,8,12));setBackground(selected?table.getSelectionBackground():row%2==0?PAPER:new Color(246,248,241));setForeground(GREEN);setFont(table.getFont());String name=table.getColumnName(col);if(name.equals("Status")){String v=String.valueOf(value).toLowerCase();setFont(table.getFont().deriveFont(Font.BOLD));setForeground(v.contains("prepar")?new Color(34,91,157):v.contains("confirm")||v.contains("pending")||v.contains("unverified")?new Color(139,91,15):v.contains("reject")||v.contains("suspend")||v.contains("out of")?new Color(155,53,40):new Color(29,113,75));}return this;}};
        t.setDefaultRenderer(Object.class,r);t.setDefaultRenderer(Integer.class,r);
    }
    static JPanel tableCard(JTable table,String title) {style(table);JPanel card=card();card.add(label(title,13,true),BorderLayout.NORTH);JScrollPane scroll=new JScrollPane(table);scroll.setColumnHeaderView(table.getTableHeader());scroll.setBorder(BorderFactory.createEmptyBorder());scroll.getViewport().setBackground(PAPER);card.add(scroll);card.setPreferredSize(new Dimension(900,400));return card;}
    static JPanel filters(JTable table,String... statuses) {JPanel p=card();p.setLayout(new BorderLayout(12,0));p.setMaximumSize(new Dimension(Integer.MAX_VALUE,72));JTextField search=new JTextField();search.setFont(new Font("Fira Code",Font.PLAIN,11));search.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(LINE),new EmptyBorder(8,12,8,12)));search.setToolTipText("Search table records");JComboBox<String> status=new gui.components.RoundedComboBox<>(statuses);status.getAccessibleContext().setAccessibleName("Filter by status");status.setFont(search.getFont());JPanel input=new JPanel(new BorderLayout(10,0));input.setOpaque(false);input.add(label("Search",11,false),BorderLayout.WEST);input.add(search);p.add(input);p.add(status,BorderLayout.EAST);Runnable update=()->{TableRowSorter<? extends TableModel> sorter=(TableRowSorter<? extends TableModel>)table.getRowSorter();sorter.setRowFilter(new RowFilter<TableModel,Integer>(){public boolean include(Entry<? extends TableModel,? extends Integer> e){boolean found=false;for(int i=0;i<e.getValueCount();i++)if(e.getStringValue(i).toLowerCase().contains(search.getText().trim().toLowerCase()))found=true;return found&&(status.getSelectedIndex()==0||e.getStringValue(e.getValueCount()-1).equalsIgnoreCase(String.valueOf(status.getSelectedItem())));}});};search.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){public void insertUpdate(javax.swing.event.DocumentEvent e){update.run();}public void removeUpdate(javax.swing.event.DocumentEvent e){update.run();}public void changedUpdate(javax.swing.event.DocumentEvent e){update.run();}});status.addActionListener(e->update.run());return p;}
}
